### PR TITLE
Rm data from filt

### PR DESCRIPTION
**Pull request by uwidocki**

### CODE REVIEW

**Comment by ashishge1** [comment]
So it looks like there could be one issue. If a string was "", then as.numeric() would cast into numeric without any warning and replace it with NA. Then the data types would not match with filtered counts.
So perhaps we should only cast the column into numeric if the column is numeric in filtered counts? (and not just because it can be cast)?

**Comment by ashishge1** [comment]
Looks good !

**Review by ashishge1 — APPROVED** [review]
Looks good with the additional checks for empty spaces. Ready to test in the pipeline I think

**Review by maha-naim — APPROVED** [review]
Looks good!

**Review by yuhjong24 — APPROVED** [review]

**Pull request merged**
